# Copyright 2018 The TensorFlow Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ==============================================================================

export TERM=xterm-256color
alias grep="grep --color=auto"
alias ls="ls --color=auto"

echo -e "\e[1;31m"
cat<<TF

**********************************************************************
*                                                                    *
* Welcome to Docker Whovian-PHY504 docker image. I hope this VM      *
* will help you learn shell, C/C++/Fortran, and Python               *
*                                                                    *
* Homework for PHY504 must compile in the University machines, but I *
* understand that running what we will learn on your laptop can help *
* you set up your research software. You can also do your HW offline *
* (ex: I take the train every day between Stony Brook and Queens),   *
* and then check if HW compiles on the lab machine afterward         *
*                                                                    *
* This image also contains multiple gcc compilers (gcc 9 / 10 / 11)  *
* They contain new features about Fortran 2008 / C++17. Have fun!    *
*                                                                    *   
* PS: Files saved outside ~/host are deleted upon exiting the VM     *
*                                                                    *
**********************************************************************

TF
echo -e "\e[0;33m"

if [[ $EUID -eq 0 ]]; then
  cat <<WARN
WARNING: You are running this container as root, which can cause new files in
mounted volumes to be created as the root user on your host machine.

To avoid this, run the container by specifying your user's userid:

$ docker run -u \$(id -u):\$(id -g) args...
WARN
else
  cat <<EXPL
You are running this container as user with ID $(id -u) and group $(id -g),
which should map to the ID and group for your user on the Docker host. Great!
EXPL
fi

# Turn off colors
echo -e "\e[m"


